import { DomainError } from "../errors";

// Matches the existing 6-char uppercase alphanumeric code generated by
// @codetype/shared/ddb-keys#generateRoomCode.
const CODE_RE = /^[A-Z0-9]{6}$/;

export class JoinCode {
  private constructor(public readonly value: string) {}

  static from(value: string): JoinCode {
    if (!CODE_RE.test(value)) {
      throw new DomainError(
        "room.invalid_code",
        400,
        `bad join code: ${value}`,
      );
    }
    return new JoinCode(value);
  }
}
